### ISSUE TITLE
Add specific function to register an event/command to a Service

### ISSUE THREAD

**Issue by debae** [event-catalog/sdk#14]
We are now creating events for every schema that we send to our confluent schema registry. 
When I do this I also want to attach the service that is either producing/consuming this event.
At this point in the time the only way to achieve this is to create the event and then create/update the service with the sends/receives attributes.

It would be much easier and more readable if there is a `addEventToService``

**Comment by boyney123** [comment]
Thanks @debae this is now added! Thanks for contribution

**Comment by boyney123** [comment]
Closing as now added.
