### ISSUE TITLE
Support listing all events

### ISSUE THREAD

**Issue by gabrielcolson** [event-catalog/sdk#41]
### Use Case

I generate a library with zod schemas from the events in my Event Catalog. I have a script that reads all `schema.json` in my catalog directory and generate the TS files but I think it would be great to have this feature in the SDK.

### Proposed Solution

Add `listEvents`, `listServices` etc. functions that return all items in a collection.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).

**Comment by boyney123** [comment]
Yeah I like it! 

Curious, so you are building a custom lib from the schemas you have in EC?

**Comment by gabrielcolson** [comment]
Yes exactly! We distribute it in a private github package that we use across our micro services.

**Comment by boyney123** [comment]
Very cool, I love the pattern of starting from schemas.

**Comment by boyney123** [comment]
@gabrielcolson would list all X, return the versions too? Or just the latest ones?

**Comment by gabrielcolson** [comment]
@boyney123 I don't use versioning at all (cf https://github.com/event-catalog/eventcatalog/issues/844) so it does not matter for my use case: the simpler the better!

**Comment by boyney123** [comment]
This is now live in `@eventcatalog/sdk@1.3.1`

New functions have been added

- getEvents
- getCommands
- getQueries
- getServices
- getDomains
- getChannels.

You can get everything, or just the latest version.

Docs updated https://www.eventcatalog.dev/docs/sdk

Let me know if you anything else @gabrielcolson , and how you get on!
